version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - GOPATH=/go/src
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/go/src/backend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
      - ./frontend/package-lock.json:/frontend/package-lock.json
      - ./frontend/package.json:/frontend/package.json