version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
      - ./frontend/package-lock.json:/frontend/package-lock.json
      - ./frontend/package.json:/frontend/package.json